openapi: 3.0.0
info:
  title: Logo schemas
  version: "1.0"
paths: { }
components:
  schemas:
    LogoMetaData:
      type: object
      properties:
        id:
          type: string
        fileName:
          type: string
        mediaType:
          type: string
          enum:
            - image/png
            - image/jpeg
        height:
          type: integer
        width:
          type: integer
    Logo:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/LogoMetaData'
        image:
          type: string
          format: binary