swagger: "2.0"
info:
  title: "Address type"
  version: "1.0"
paths: {}
definitions:
  Address:
    description: 'An address'
    type: object
    properties:
      streetName:
        type: string
      streetRrnCode:
        $ref: "../belgif/location/v1/location-v1.yaml#/definitions/StreetRrnCode"
      houseNumber:
        type: string
      boxNumber:
        type: string
      postCode:
        type: string
      municipalityName:
        type: string
      municipalityCode:
        $ref: "../belgif/location/v1/location-v1.yaml#/definitions/MunicipalityCode"
      belgianRegionCode:
        $ref: "../belgif/location/v1/location-v1.yaml#/definitions/BelgianRegionCode"
      countryNisCode:
        $ref: "../belgif/location/v1/location-v1.yaml#/definitions/CountryNisCode"
      country:
        type: string
    required:
      - streetName
      - houseNumber 
      - postCode
      - municipalityName 
