swagger: "2.0"
info:
  title: "EmployerClass type"
  version: "1.0"
paths: {}
definitions:
  EmployerClass:
    description: 'The employer class as defined here http://rest-reference.test.paas.socialsecurity.be/REST/demo/v1/appendices/employerclasses'
    type: object
    properties:
      value:
        type: string
      description:
        $ref: './LocalizedString.yaml#/definitions/LocalizedString'
    required:
    - value
