swagger: "2.0"
info:
  title: "EmployerCollection type"
  version: "1.0"
paths: {}
definitions:
  EmployerCollection:
    description: A collection of employers
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/EmployerLink'
      total:
        description: "the total number of items across all pages"
        type: integer
        format: "int32"
      pageSize: 
        description: "Maximum number of items per page, default 5"
        type: "integer"
        default: 5
        format: "int32"
      first:
        type: string
        format: uri
        description: The URI of the first page
        example: /item?page=1&pageSize=5
      last:
        type: string
        format: uri
        description: The URI of the last page
        example: /item?page=13&pageSize=5
      next:
        type: string
        format: uri
        description: The URI of the next page
        example: /item?page=5&pageSize=5
      prev:
        type: string
        format: uri
        description: The URI of the previous page
        example: /item?page=3&pageSize=5 
      self:
        type: string
        format: uri
        description: The URI of the current page
        example: /item?page=4&pageSize=5 
        
  EmployerLink:
    type: object
    properties:
      href:
        description: 'Any absolute URI that is using http or https protocol'
        type: string
        format: uri
      title:
        description: 'Its value is a string and is intended for labelling the link
          with a human-readable identifier (as defined by [RFC5988]).'
        type: string
      employerId:
        $ref: './Employer.yaml#/definitions/EmployerId'
      enterpriseNumber:
        $ref: '../belgif/organization/identifier/v1/organization-identifier-v1.yaml#/definitions/EnterpriseNumber'
