swagger: "2.0"
info:
  title: "Employer type"
  version: "1.0"
paths: {}
definitions:
  Employer:
    type: object
    properties:
      name:
        type: string
      employerId:
        allOf:
          - $ref: '#/definitions/EmployerId'  
          - readOnly: true
      registeredOrganization:
        $ref: './RegisteredOrganizationCollection.yaml#/definitions/RegisteredOrganizationLink'
      employerClasses:
        type: array
        items:
          $ref: '../belgif/common/v1/common-v1.yaml#/definitions/HttpLink'
    required:
      - name
      - registeredOrganization
    example:
      {
        "employerId": "164893015",
        "name": "Esprit",
        "registeredOrganization": {
          "enterpriseNumber": "0433072831"
        }
      }
  EmployerId: #TODO: use belgif type when not in beta anymore
    description: 'Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration'
    type: string
    pattern: '^5?\d{9}$' # first digit 5 indicates a provisional NSSO number
    example: '000100006'

