swagger: "2.0"
info:
  title: "Registered Organization type"
  version: "1.0"
paths: {}
definitions:
  RegisteredOrganization:
    type: object
    properties:
      name:
        type: string
      state:
        type: string
        enum:
          - active
          - inactive
      enterpriseNumber:
        $ref: '../belgif/organization/identifier/v1/organization-identifier-v1.yaml#/definitions/EnterpriseNumber'
      startDate:
        type: string
        format: date
      address:
        $ref: './Address.yaml#/definitions/Address'
      lastModificationDate:
        type: string
        format: date-time
    required:
    - name
    - enterpriseNumber 
