swagger: "2.0"
info:
  title: data types related to organizations
  version: 1.0.0
paths: {}
definitions:
  CbeNumber:
    description: Identifier issued by CBE for either an organization or a site (establishment) of an organization
    type: string
    pattern: '^[0-8]\d{9}$'
    #TODO: synchronize descriptions with vocabularies
  EnterpriseNumber:
    description: Identifier issued by CBE for a registered organization
    type: string
    pattern: '^[0|1]\d{9}$'
  EstablishmentUnitNumber:
    description: Identifier issued by CBE for a site (establishment) of an organization 
    type: string
    pattern: '^[2-8]\d{9}$'